include build/make/target/board/generic_arm64/BoardConfig.mk
include device/phh/treble/board-base.mk

ifeq ($(BOARD_SYSTEMIMAGE_PARTITION_RESERVED_SIZE),)
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2147483648
else
BOARD_SYSTEMIMAGE_PARTITION_RESERVED_SIZE := 33554432
endif



BUILD_BROKEN_MISSING_REQUIRED_MODULES := true

SELINUX_IGNORE_NEVERALLOWS := true

ALLOW_MISSING_DEPENDENCIES=true


BOARD_EXT4_SHARE_DUP_BLOCKS := false
